import tkinter as tk
cal=""
def add(sym):
    global cal
    cal += str(sym)
    txtres.delete(1.0, "end")
    txtres.insert(1.0, cal)
def elav():
    global cal
    try:
        cal=str(eval(cal))
        txtres.delete(1.0, "end")
        txtres.insert(1.0, cal)
    except:
        clr()
        txtres.insert(1.0,"Error")
def clr():
    global cal
    txtres.delete(1.0, "end")

root =tk.Tk()
root.geometry("300x295")
txtres=tk.Text(root, height=2,width=17,font=("Arial",24),bg="light gray")
txtres.grid(columnspan=6)
b1=tk.Button(root, text='1', command=lambda:add(1),width=5,font=("Arial",14),bg="gray64")
b1.grid(row=2,column=1)
b2=tk.Button(root, text='2', command=lambda:add(2),width=5,font=("Arial",14),bg="gray64")
b2.grid(row=2,column=2)
b3=tk.Button(root, text='3', command=lambda:add(3),width=5,font=("Arial",14),bg="gray64")
b3.grid(row=2,column=3)
b4=tk.Button(root, text='4', command=lambda:add(4),width=5,font=("Arial",14),bg="gray64")
b4.grid(row=3,column=1)
b5=tk.Button(root, text='5', command=lambda:add(5),width=5,font=("Arial",14),bg="gray64")
b5.grid(row=3,column=2)
b6=tk.Button(root, text='6', command=lambda:add(6),width=5,font=("Arial",14),bg="gray64")
b6.grid(row=3,column=3)
b7=tk.Button(root, text='7', command=lambda:add(7),width=5,font=("Arial",14),bg="gray64")
b7.grid(row=4,column=1)
b8=tk.Button(root, text='8', command=lambda:add(8),width=5,font=("Arial",14),bg="gray64")
b8.grid(row=4,column=2)
b9=tk.Button(root, text='9', command=lambda:add(9),width=5,font=("Arial",14),bg="gray64")
b9.grid(row=4,column=3)
b0=tk.Button(root, text='0', command=lambda:add(0),width=5,font=("Arial",14),bg="gray64")
b0.grid(row=5,column=2)
bplus=tk.Button(root, text='+', command=lambda:add("+"),width=5,font=("Arial",14),bg="gray64")
bplus.grid(row=2,column=4)
bminus=tk.Button(root, text='-', command=lambda:add("-"),width=5,font=("Arial",14),bg="gray64")
bminus.grid(row=3,column=4)
bmul=tk.Button(root, text='*', command=lambda:add("*"),width=5,font=("Arial",14),bg="gray64")
bmul.grid(row=4,column=4)
bdiv=tk.Button(root, text='/', command=lambda:add("/"),width=5,font=("Arial",14),bg="gray64")
bdiv.grid(row=5,column=4)
blpar=tk.Button(root, text='(', command=lambda:add("("),width=5,font=("Arial",14),bg="gray64")
blpar.grid(row=5,column=1)
brpar=tk.Button(root, text=')', command=lambda:add(")"),width=5,font=("Arial",14),bg="gray64")
brpar.grid(row=5,column=3)
bdecimal=tk.Button(root, text='.', command=lambda:add("."),width=5,font=("Arial",14),bg="gray64")
bdecimal.grid(row=6,column=3)
bcls=tk.Button(root, text='C', command=clr,width=12,font=("Arial",14),bg="gray64")
bcls.grid(row=6,column=1,columnspan=2)
beqls=tk.Button(root, text='=', command=elav,width=5,font=("Arial",14),bg="gray64")
beqls.grid(row=6,column=4)
root.title("Calaculator")
root.mainloop()